{{- if .Values.service_auth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metaflow.fullname" . }}-auth
type: Opaque
stringData:
  auth: |
    metaflowuser:$apr1$hiVMFO6O$Kjr1QEuWdbCBh144mLDKz0
{{- end }}