{{- $postgresSvcPort := "5432" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metaflow.fullname" . }}
  labels:
    {{- include "metaflow.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "metaflow.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "metaflow.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "metaflow.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MF_METADATA_DB_HOST
              value: {{ include "metaflow.fullname" . }}-postgres
            - name: MF_METADATA_DB_NAME	
              value: "{{ .Values.postgres.database | default "metaflow" }}"
            - name: MF_METADATA_DB_PORT
              value: "{{ $postgresSvcPort }}"
            - name: MF_METADATA_DB_PSWD
              value: "{{ required "Database password is required (for now)" .Values.postgres.password }}"
            - name: MF_METADATA_DB_USER
              value: "{{ .Values.postgres.user | default "master" }}"
          ports:
            - name: metadata
              containerPort: 8080
              protocol: TCP
            - name: upgrades
              containerPort: 8082
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
