{{- if .Values.ingress.enabled -}}
{{- $fullName := include "metaflow.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "metaflow.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{- if .Values.service_auth.enabled }}
    nginx.ingress.kubernetes.io/auth-secret: {{ include "metaflow.fullname" . }}-auth
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - http:
        paths:
          - path: /(.*)
            backend:
              serviceName: {{ include "metaflow.fullname" . }}
              servicePort: 8080
          - path: /update_api/(.*)
            backend:
              serviceName: {{ include "metaflow.fullname" . }}
              servicePort: 8082
  {{- end }}