apiVersion: v1
kind: Service
metadata:
  name: {{ include "metaflow.fullname" . }}
  labels:
    {{- include "metaflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metadata
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: upgrades
      port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    {{- include "metaflow.selectorLabels" . | nindent 4 }}
